### ISSUE TITLE
Electronic voting votes are final

### ISSUE THREAD

**Issue by kaduk** [ietf-llc/policies-consultation#3]
https://github.com/ietf-llc/policies-consultation/blob/master/Electronic-Voting-00.md notes that a vote is final once it has been submitted, which renders moot any subsequent discussion among the board or new facts that may come to light.  This can lead to very awkward dynamics where a flurry of votes come in initially before a proper discussion occurs, leading to "trapped votes".  Some mechanism for changing a vote subject to discussion seems to be in order.

**Comment by jlivingood** [comment]
Votes are not discussion tools or a replacement for discussion. I did make an update to allow for canceling a vote to address this however. Will send to counsel for review.

**Comment by jlivingood** [comment]
Confirming that counsel agrees with our view, so confirming no change to voting policy.

From counsel:
We agree that this change likely creates more issues than it solves by opening up a whole line of questions regarding the VA's authority and appropriate grounds for cancellation. In practicality, we don't think there is a compelling need for such an interim vote cancelation process. Votes are generally only called for after the opportunity for and actual substantive discussion has occurred. In the event a vote is no longer appropriate or additional facts come to light in discussion after a few votes are cast, the Board would assumedly recognize the additional factors and call for a new vote based on the new facts. 

Otherwise, we would need to carefully think through a whole host of thorny issues to control for the relevant parameters and proper exercise of the authority to cancel such votes.
